# Generated by Django 5.0.2 on 2024-02-18 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='author',
            field=models.ForeignKey(blank=True, default='user.UserAccount', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='is_Director',
            field=models.BooleanField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='is_branch_chief',
            field=models.BooleanField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='is_dojoOperator',
            field=models.BooleanField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=2),
        ),
    ]
