# Generated by Django 5.0.2 on 2024-02-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos', '0003_alter_dojos_author_alter_dojos_is_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='is_Director',
            field=models.BooleanField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='is_branch_chief',
            field=models.BooleanField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=10),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='is_dojoOperator',
            field=models.BooleanField(choices=[('si', 'Si'), ('no', 'No')], default='no', max_length=10),
        ),
    ]
