# Generated by Django 5.0.2 on 2024-02-18 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos', '0005_alter_dojos_is_director_alter_dojos_is_branch_chief_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='author',
            field=models.ForeignKey(default='user.UserAccount', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
