# Generated by Django 5.0.2 on 2024-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos', '0006_alter_dojos_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='zona',
            field=models.CharField(blank=True, choices=[('Norte', 'Norte'), ('Centro', 'Centro'), ('Sur', 'Sur')], max_length=10),
        ),
    ]
