# Generated by Django 5.0.2 on 2024-02-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos', '0007_alter_dojos_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='is_Director',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='is_branch_chief',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='is_dojoOperator',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
    ]
