# Generated by Django 5.0.2 on 2024-02-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos', '0008_alter_dojos_is_director_alter_dojos_is_branch_chief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='is_branch_chief',
            field=models.CharField(blank=True, choices=[('---', '---'), ('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
    ]
