# Generated by Django 5.0.2 on 2024-02-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos', '0009_alter_dojos_is_branch_chief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='cargo',
            field=models.CharField(blank=True, choices=[('---', '---'), ('Senpai', 'Senpai'), ('Sensei', 'Sensei'), ('Shihan', 'Shihan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='grado',
            field=models.CharField(blank=True, choices=[('---', '---'), ('1er kyu', '1er kyu'), ('1er Dan', '1er Dan'), ('2do Dan', '2do Dan'), ('3er Dan', '3er Dan'), ('4to Dan', '4to Dan'), ('5to Dan', '5to Dan'), ('6to Dan', '6to Dan')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='is_Director',
            field=models.CharField(blank=True, choices=[('---', '---'), ('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='is_dojoOperator',
            field=models.CharField(blank=True, choices=[('---', '---'), ('Si', 'Si'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='zona',
            field=models.CharField(blank=True, choices=[('---', '---'), ('Norte', 'Norte'), ('Centro', 'Centro'), ('Sur', 'Sur')], max_length=10),
        ),
    ]
