# Generated by Django 5.0.2 on 2024-02-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos', '0011_alter_dojos_cargo_alter_dojos_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='is_Director',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='is_branch_chief',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='dojos',
            name='is_dojoOperator',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
