# Generated by Django 5.0.2 on 2024-02-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos', '0012_alter_dojos_is_director_alter_dojos_is_branch_chief_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dojos',
            options={'ordering': ('status',)},
        ),
    ]
