# Generated by Django 5.0.7 on 2024-07-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dojos', '0013_alter_dojos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojos',
            name='zona',
            field=models.CharField(blank=True, choices=[('Nacional', 'Nacional'), ('Norte', 'Norte'), ('Centro', 'Centro'), ('Sur', 'Sur')], max_length=10),
        ),
    ]
