# Generated by Django 5.0.7 on 2024-07-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackBelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('grade', models.CharField(choices=[('1st Dan', '1st Dan'), ('2nd Dan', '2nd Dan'), ('3rd Dan', '3rd Dan'), ('4th Dan', '4th Dan'), ('5th Dan', '5th Dan'), ('6th Dan', '6th Dan')], max_length=50)),
                ('Dojo', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.CharField(blank=True, choices=[('Norte', 'Norte'), ('Centro', 'Centro'), ('Sur', 'Sur')], max_length=50)),
            ],
            options={
                'verbose_name': 'Black Belt',
                'verbose_name_plural': 'Black Belts',
                'ordering': ['first_name', 'grade', 'zone'],
            },
        ),
    ]
