# Generated by Django 5.0.2 on 2024-02-18 00:18

import apps.blog.models
import ckeditor.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=255, unique=True)),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to=apps.blog.models.blog_thumbnail_directory)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('time_read', models.IntegerField(blank=True, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='blog/files/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'ordering': ('-status',),
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
            ],
        ),
    ]
