export const GET_DOJO_SUCCESS = "GET_DOJO_SUCCESS";
export const GET_DOJO_FAIL = "GET_DOJO_FAIL";
export const GET_AUTHOR_INSTRUCTOR_LIST_SUCCESS = "GET_AUTHOR_INSTRUCTOR_LIST_SUCCESS";
export const GET_AUTHOR_INSTRUCTOR_LIST_FAIL = "GET_AUTHOR_INSTRUCTOR_LIST_FAIL";
