# Generated by Django 5.0.7 on 2024-07-24 20:31

import apps.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=apps.gallery.models.blog_thumbnail_directory),
        ),
    ]
