# Generated by Django 5.0.7 on 2024-07-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='link_drive',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
