export const GET_GALLERY_LIST_SUCCESS = 'GET_GALLERY_LIST_SUCCESS';
export const GET_GALLERY_LIST_FAIL = 'GET_GALLERY_LIST_FAIL';
export const GET_GALLERY_DETAIL_SUCCESS = 'GET_GALLERY_DETAIL_SUCCESS';
export const GET_GALLERY_DETAIL_FAIL = 'GET_GALLERY_DETAIL_FAIL';
