# Generated by Django 5.0.2 on 2024-02-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='date_event',
            new_name='date',
        ),
    ]
