# Generated by Django 5.0.2 on 2024-02-15 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_alter_calendario_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='date',
        ),
    ]
