# Generated by Django 5.0.2 on 2024-02-15 02:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_remove_calendario_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
