# Generated by Django 5.0.2 on 2024-03-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0009_alter_calendario_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
